on:
  push:
  workflow_dispatch:
  pull_request:

    
jobs:
  checkout:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - env:
          FOO: ${{ secrets.FOO }}
        run: |
          echo ${FOO:2:1}
